# Generated by Django 5.0.2 on 2024-02-07 19:41

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SmrtProperties",
            fields=[
                ("imb_ID", models.SmallIntegerField(primary_key=True, serialize=False)),
                ("imb_Category", models.CharField(max_length=60, null=True)),
                ("imb_Name", models.CharField(max_length=120, null=True)),
                ("imb_MLS", models.FloatField(null=True)),
                ("imb_Type", models.CharField(max_length=50, null=True)),
                ("imb_City", models.CharField(max_length=50, null=True)),
                ("imb_State", models.CharField(max_length=50, null=True)),
                ("imb_Area", models.CharField(max_length=80, null=True)),
                ("imb_Bedrooms", models.SmallIntegerField(null=True)),
                ("imb_Bathrooms", models.SmallIntegerField(null=True)),
                ("imb_Size", models.FloatField(null=True)),
                (
                    "imb_Price",
                    models.DecimalField(decimal_places=2, max_digits=12, null=True),
                ),
                ("imb_Currency", models.CharField(max_length=30, null=True)),
                ("imb_New_Flag", models.BooleanField(null=True)),
                ("imb_Owner", models.CharField(max_length=80, null=True)),
                ("imb_Agent", models.CharField(max_length=80, null=True)),
                ("imb_Prom_Disc", models.BooleanField(null=True)),
                ("imb_Description", models.CharField(max_length=200, null=True)),
                ("imb_Active", models.BooleanField(null=True)),
            ],
        ),
    ]
