# Generated by Django 5.0.2 on 2024-02-27 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_site', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='smrtproperties',
            name='imb_Image',
            field=models.ImageField(blank=True, db_column='IMBIMAGE', null=True, upload_to='property_images/'),
        ),
    ]
