# Generated by Django 5.0.2 on 2024-02-07 21:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web_site", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="smrtproperties",
            name="imb_ID",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
