# Generated by Django 5.0.2 on 2024-02-27 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_site', '0002_smrtproperties_imb_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='smrtproperties',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='smrtproperties',
            table='SMRTPROPERTIES',
        ),
    ]
