# Generated by Django 5.0.2 on 2024-02-27 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_site', '0003_alter_smrtproperties_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smrtproperties',
            name='imb_Image',
            field=models.ImageField(blank=True, db_column='IMBIMAGE', null=True, upload_to='static/images/property_images/'),
        ),
    ]
