# Generated by Django 5.0.2 on 2024-03-06 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_site', '0004_alter_smrtproperties_imb_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='smrtproperties',
            name='imb_Description_Es',
            field=models.CharField(db_column='IMBDESCRIPTIONES', max_length=200, null=True),
        ),
    ]
