# Generated by Django 5.0.2 on 2024-03-07 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_site', '0005_smrtproperties_imb_description_es'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smrtproperties',
            name='imb_Image',
        ),
    ]
