# Generated by Django 5.0.2 on 2024-03-07 16:32

import django.db.models.deletion
import web_site.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_site', '0006_remove_smrtproperties_imb_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=web_site.models.get_image_path)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_site.smrtproperties')),
            ],
            options={
                'db_table': 'PROPERTYIMAGES',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='smrtproperties',
            name='imb_Image',
            field=models.ForeignKey(blank=True, db_column='IMBIMAGE', null=True, on_delete=django.db.models.deletion.CASCADE, to='web_site.propertyimage'),
        ),
    ]
