# Generated by Django 5.0.2 on 2024-03-07 17:50

import web_site.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_site', '0007_propertyimage_smrtproperties_imb_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyimage',
            name='image',
            field=models.ImageField(blank=True, db_column='IMAGES', null=True, upload_to=web_site.models.get_image_path),
        ),
    ]
