# Generated by Django 5.0.2 on 2024-03-12 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_site', '0008_alter_propertyimage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smrtproperties',
            name='imb_Image',
        ),
    ]
