# Generated by Django 5.0.2 on 2024-03-12 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_site', '0009_remove_smrtproperties_imb_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smrtproperties',
            name='imb_Active',
        ),
    ]
