# Generated by Django 5.0.2 on 2024-03-12 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_site', '0010_remove_smrtproperties_imb_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='smrtproperties',
            name='imb_Active',
            field=models.BooleanField(db_column='IMBACTIVE', null=True),
        ),
    ]
