# Generated by Django 5.0.2 on 2024-03-14 18:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_site', '0011_smrtproperties_imb_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='smrtproperties',
            name='imb_Creation_Time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
