# Generated by Django 5.0.2 on 2024-03-14 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_site', '0012_smrtproperties_imb_creation_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asociados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('contacto', models.CharField(max_length=255)),
                ('area_expertis', models.CharField(max_length=255)),
                ('puesto', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('imagen', models.ImageField(upload_to='asociates/<django.db.models.fields.CharField>/<django.db.models.fields.CharField>')),
            ],
            options={
                'verbose_name': 'Asociado',
                'verbose_name_plural': 'Asociados',
            },
        ),
    ]
