# Generated by Django 5.0.2 on 2024-03-15 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_site', '0013_asociados'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asociados',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='asociados',
            table='ASOCIATES',
        ),
    ]
