# Generated by Django 5.0.2 on 2024-03-15 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_site', '0014_alter_asociados_options_alter_asociados_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='asociados',
            table=None,
        ),
    ]
