# Generated by Django 5.0.2 on 2024-03-19 15:07

import web_site.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_site', '0016_alter_asociados_imagen_alter_propertyimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asociados',
            name='imagen',
            field=models.ImageField(blank=True, upload_to=web_site.models.get_asociate_path),
        ),
    ]
