# Generated by Django 5.0.2 on 2024-03-19 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_site', '0017_alter_asociados_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='asociados',
            name='activo',
            field=models.BooleanField(null=True),
        ),
    ]
